server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE  #???????





