server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE  #???????


nacos:
  service-address: localhost
  port: 8848
dubbo:
  service:
    version: 1.0.0
  application:
    name: wj-api-gateway-consumer
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}



