server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_self
          uri: http://localhost:8080
          predicates:
            - Method=POST
            - Path=/api/invoke/**
          filters:
            - StripPrefix=2
            - PrefixPath=/api/name/user

        - id: api_other
          uri: https://v1.hitokoto.cn
          predicates:
            - Method=GET
            - Path=/api/invoke/**
          filters:
            - StripPrefix=2
            - PrefixPath=/



logging:
  level:
    org.springframework.cloud.gateway: TRACE  #???????


nacos:
  service-address: localhost
  port: 8848
dubbo:
  service:
    version: 1.0.0
  application:
    name: wj-api-gateway-consumer
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}



